### ISSUE TITLE
COPYING appears to contradict actual license

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/cmockery#16]
```
COPYING[1] (incorrectly) indicates that cmockery is distributed under a BSD
license.

[1] http://code.google.com/p/cmockery/source/browse/trunk/COPYING

```

Original issue reported on code.google.com by `matsl...@gmail.com` on 16 Nov 2009 at 10:36

**Comment by mbrukman** [comment]
@stewartmiles — I just noticed this myself; can you please look into this?

* [`COPYING`][copying] contains the BSD license
* [`LICENSE.txt`][license-txt] contains the Apache 2.0 license

Which one is the correct license for this repo? Google standard is to have only a `LICENSE` or `LICENSE.txt` file, which suggests the `COPYING` file is extra in this repo.

[copying]: https://github.com/google/cmockery/blob/45f7ec09307ea40b1e2c3d4ac18d3af30825e0b3/COPYING
[license-txt]: https://github.com/google/cmockery/blob/45f7ec09307ea40b1e2c3d4ac18d3af30825e0b3/LICENSE.txt

**Comment by stewartmiles** [comment]
It should be Apache 2.0.

**Comment by mbrukman** [comment]
@stewartmiles — can you just remove the `COPYING` file, since we already have a `LICENSE.txt` that has the Apache 2.0 license? Having both, even if they're the same content, would be confusing as well.

**Comment by stewartmiles** [comment]
Fixed in https://github.com/google/cmockery/commit/fe1b69fcdf42951cc130ce2b3e4f076ce575127e

**Comment by mbrukman** [comment]
Thanks, @stewartmiles!
