### ISSUE TITLE
Re-create historical releases (0.1.0, 0.1.1, 0.1.2) on GitHub

### ISSUE THREAD

**Issue by mbrukman** [google/cmockery#61]
We can see the past release history in the [`ChangeLog`][changelog]:

```
Mon Sep 15 17:21:22 2008 Google Inc. <opensource@google.com>
	* cmockery: version 0.12
	* Made it possible to specify additional compiler, lib tool and link 
	flags on Windows.
	* Added Windows makefile to the tar ball.

Fri Aug 29 10:50:46 2008  Google Inc. <opensource@google.com>

	* cmockery: version 0.11
	* Made it possible to specify executable, library and object output 
	  directories.

Tue Aug 26 10:18:02 2008  Google Inc. <opensource@google.com>

	* cmockery: initial release:
	  A lightweight library to simplify and generalize the process of 
	  writing unit tests for C applications.
```

We just need to find the right commits that were the cut-offs for each of the release, and create an appropriate release tag for each of those points.

For v0.1.2, since that was the last release, we also have [a pointer to the full tarball courtesy of Homebrew][homebrew-cmockery] which is [hosted on GCS][gcs-cmockery] which can be used to identify the right commit point.

Interestingly enough, `git log` also shows the release tags added to the repo in SVN, but there are several such commits for every SVN tag. We can also look at the commit history of the `ChangeLog` itself to identify the release points.

[changelog]: https://github.com/google/cmockery/blob/1a9f9f8ff4b0495b407df5fb4a32b968074d4628/ChangeLog
[homebrew-cmockery]: https://github.com/Homebrew/homebrew-core/blob/65b8412c952d9b42e0e2c32642f48d6afd439c4f/Formula/cmockery.rb#L4
[gcs-cmockery]: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/cmockery/cmockery-0.1.2.tar.gz

**Comment by mbrukman** [comment]
Turns out, we actually have a branch for each release:

* https://github.com/google/cmockery/tree/cmockery-0.1/trunk
* https://github.com/google/cmockery/tree/cmockery-0.11/trunk
* https://github.com/google/cmockery/tree/cmockery-0.12/trunk

and we can just use the last commit on each of these branches to create a release tag on GitHub.

However, all of the historical releases will have everything under the `trunk` directory since the cleanup happened in 2015 while these releases happened much earlier in 2008.

What we can do to create clean historical releases is as follows:

* for each branch (`cmockery-0.1`, `cmockery-0.11`, `cmockery-0.12`), add another commit to move everything from `trunk/*` to top-level
* create a release for each of the historical versions
* resume future releases to be done from the relevant commit on `master`

@stewartmiles, thoughts / concerns on this proposed plan?

**Comment by stewartmiles** [comment]
All seems fine to me.  Though I wonder why we would want to restore these
historical releases at all?  Is there value is this for any users?

**Comment by mbrukman** [comment]
By "restoring" I simply mean creating appropriate version tags, such that they show up on https://github.com/google/cmockery/releases and are easily downloadable; it also makes it trivial for users to diff two releases to see what changed, e.g., from 0.1.2 to the next release.

Also, for continuity, so that it's always easy to download a 0.1 or 0.1.2 release; right now, there's only the archive on GCS from the Google Code export that's referenced in Homebrew (see first comment), but the GCS archives may be theoretically removed in the future; this makes this repo self-contained from here on out.

**Comment by stewartmiles** [comment]
Ah gotcha, sounds good.

**Comment by mbrukman** [comment]
The cleanup changes have been merged and historical releases have been created:

* https://github.com/google/cmockery/releases/tag/v0.1.0
* https://github.com/google/cmockery/releases/tag/v0.1.1
* https://github.com/google/cmockery/releases/tag/v0.1.2
